modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"

[[mods]]
modId = "bloomingnature"
version = "${version}"
displayName = "[Let's Do] BloomingNature"
authors = "satisfy"
description = '''
Hello wanderer! The overworld has changed: New flowers bloom, fresh woods grow, and reshaped biomes await your footsteps.
'''
logoFile = "pack.png"
displayURL = "https://www.lets-do.ch"

[[dependencies.bloomingnature]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bloomingnature]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bloomingnature]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bloomingnature]]
modId = "foundation"
type = "required"
versionRange = "[1.0.3,)"
ordering = "AFTER"
side = "BOTH"
