modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"

[[mods]]
modId = "bloomingnature"
version = "${version}"
displayName = "[Let's Do] BloomingNature"
authors = "satisfy"
description = '''
Explore a redesigned overworld: new animals, reshaped biomes, livelier landscapes
'''
logoFile = "pack.png"

[[dependencies.bloomingnature]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bloomingnature]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bloomingnature]]
modId = "architectury"
type = "required"
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"