modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"

[[mods]]
modId = "bloomingnature"
version = "${version}"
displayName = "[Let's Do] BloomingNature"
authors = "satisfy"
description = '''
Explore a redesigned overworld: new animals, reshaped biomes, livelier landscapes
'''
logoFile = "pack.png"

[[mixins]]
config = "bloomingnature-common.mixins.json"

[[dependencies.bloomingnature]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bloomingnature]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bloomingnature]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bloomingnature]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.10,)"
ordering = "AFTER"
side = "BOTH"
